Home work14
JenyaHutsul/Hillel-Pro pull request #14
Opened 2022-04-16 13:29 UTC by JenyaHutsul

2022-04-18 19:01 UTC, dkhovrich requested changes

2022-04-18 19:01 UTC, dkhovrich commented on home work14/script.js
> +    if(localStorage){
Для чего это условие? Все современные браузеры поддерживают localStorage. Можно его убрать.

2022-04-18 19:01 UTC, dkhovrich commented on home work14/script.js
> +            return null;
Вы тут возвращаете `null` и дальше по коду используете `messageObj`:
`messageObj.remove(span.textContent)`
Если будет null, то все сломается. В случае, если данных нет в сторадже, лучше использовать дефолтные (пустой объект в Вашем случае).

2022-04-18 19:01 UTC, dkhovrich commented on home work14/script.js
> +            localStorage.clear();
Это очень радикально - очищать все данные. Лучше так: `localStorage.remove("obj")`

2022-04-19 13:02 UTC, JenyaHutsul commented on home work14/script.js
> +            return null;
Да, я не проверил, как будет отрабатывать с null'ом, я когда писал, **return null**, я был уверен, что я выйду из блока if, а не верну значение из всей функции. Но на этом проблема не закончилась, если вернуть пустой объект, то **messageObj** у меня будет пустой объект, а дальше я много раз обращаюсь к его методам. Методом проб и дебаггера, понял что нужно использовать такой же **return { add, remove, show, obj }** как и ниже

2022-04-19 13:02 UTC, JenyaHutsul commented on home work14/script.js
> +    if(localStorage){
Я думал, это проверит, есть ли у нас localstorage, а оказывается надо проверять длину.  Если есть, что-то, то парсим localstorage.

2022-04-19 13:03 UTC, dkhovrich commented on home work14/script.js
> +    if(localStorage){
Не понял насчет длины. Длину чего проверять?

2022-04-19 13:05 UTC, dkhovrich commented on home work14/script.js
> +            return null;
Я бы предложил чуть проще сделать. Вынести отдельно загрузку данных из стораджа. Если при парсинге ошибка, то вернуть пустые данные (объект или массив). Наверняка методы **add, remove, show** будут нормально работать с пустым объектом или массивом.

Это ситуация, которая будет при первом старте программы. Когда сохраненных данных еще нет.

2022-04-19 13:50 UTC, YevhenHutsul commented on home work14/script.js
> +    if(localStorage){
Я хотел проверять, есть ли у нас что-то в storage, но сейчас посидев понял, что это не лучший метод проверки на наличие, чего то в storage, можно обращаться к ключу "obj", ну в нем будет пустой объект и он при такой проверке всегда будет правдой

2022-04-19 13:51 UTC, JenyaHutsul commented on home work14/script.js
> +            return null;
Посмотрите пожалуйста, последний коммит, я то сделал?

2022-04-19 16:07 UTC, dkhovrich requested changes

2022-04-19 16:07 UTC, dkhovrich commented on home work14/script.js
> +    for (const key in data) {
Этому циклу тут не место. Судя по названию ф-ции, она загружает данные из стораджа. А тут она еще добавляет их в **ul**. Это лучше сделать в другом месте (за пределами этой ф-ции).

2022-04-19 16:07 UTC, dkhovrich commented on home work14/script.js
> +            return null;
Да, все правильно сделали. Есть вопрос к циклу внутри ф-ции. Его тут задал: https://github.com/JenyaHutsul/Hillel-Pro/pull/14#discussion_r853248579

2022-04-19 19:29 UTC, JenyaHutsul commented on home work14/script.js
> +    for (const key in data) {
Доброй ночи! Проверьте последний коммит пожалуйста. Там я добавил 2 коммита, без понятия каким образом, они одинаковые

2022-04-19 20:02 UTC, dkhovrich commented on home work14/script.js
> +    for (const key in data) {
Теперь все хорошо :)

2022-04-19 20:02 UTC, dkhovrich approved these changes

2022-04-20 11:21 UTC, JenyaHutsul commented on home work14/script.js
> +    for (const key in data) {
Вот это кураторство! Не думал, что ночью ответите! Спасибо :)

2022-04-21 12:55 UTC, closed without merging