made hm6
JenyaHutsul/Hillel-Pro pull request #4
Opened 2022-02-04 10:43 UTC by JenyaHutsul

2022-02-04 16:21 UTC, dkhovrich requested changes

2022-02-04 16:21 UTC, dkhovrich commented on script.js
> +        const keysA = Object.keys(a).toString();
Преобразование к строке и сравнение строк - грязный хак :)
Попробуйте, пожалуйста, решить эту задачу через циклы.

2022-02-04 16:21 UTC, dkhovrich commented on script.js
> +    if (isObj(target) && isObj(origin)) {
Лучше инвертировать такие условия:
```
if (!isObj(target) || !isObj(origin)) {
console.error("Передан не объект")
return;
}
```

2022-02-04 16:21 UTC, dkhovrich commented on script.js
> +    if (typeof str === "string") {
Тут тоже лучше инвертировать условие (как в предыдущем комментарии).

2022-02-04 16:21 UTC, dkhovrich commented on script.js
> +            if (obj[current]) {
Тут все правильно. Хорошее решение!
Попробуйте вместо if/else использовать тут тернарный оператор.

2022-02-04 16:21 UTC, dkhovrich commented on script.js
> +function copy(target, origin) {
Отличное решение!

2022-02-07 17:57 UTC, dkhovrich approved these changes

2022-02-07 17:57 UTC, dkhovrich commented on script.js
> +    debugger;
debugger такие вещи нужно удалять перед коммитом :)

2022-02-07 18:04 UTC, YevhenHutsul commented on script.js
> +    debugger;
согласен, засмотрелся наверное :C

2022-02-09 10:46 UTC, closed without merging